version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:18.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: AWS CLI
          command: |
            apt update
            apt-get install -y python-pip
            pip install awscli
      - run:
          name: Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build
          command: |
            docker build . -t 764370704799.dkr.ecr.us-west-2.amazonaws.com/saul:latest
            eval $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
            docker push 764370704799.dkr.ecr.us-west-2.amazonaws.com/saul:latest
